[window]
opacity = 0.8

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.normal]
black = "#000000"
blue = "#bd93f9"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[colors.bright]
black = "#575b70"
blue = "#d6acff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[font]
size = 11
offset = { y = -1 }
normal = { family = "IosevkaTerm NF", style = "Regular" }
bold = { family = "IosevkaTerm NF", style = "Bold" }
italic = { family = "IosevkaTerm NF", style = "Italic" }
bold_italic = { family = "IosevkaTerm NF", style = "Bold Italic" }

[keyboard]
bindings = [
{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
