format = """
$all$jobs$line_break$character
"""
add_newline = false

[character]
success_symbol = "[\u2570\u2500>](bold green)"
error_symbol = "[\u2570\u2500>](bold green)"

[username]
format = "[\u256d\u2500](bold green) [$user]($style) "
show_always = true

[hostname]
format = "@ [$hostname]($style) "
style = "bold fg:#d75f5f"
ssh_only = false

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
style = "bold blue"

[git_status]
staged = "[+\\(${count}\\)](fg:green bold)"
untracked = "[%\\(${count}\\)](fg:#ff92df bold)"
modified = "[!\\(${count}\\)](fg:red bold)"
stashed = "[?\\(${count}\\)](fg:yellow bold)"
renamed = "[r\\(${count}\\)](fg:cyan bold)"
deleted = "[d\\(${count}\\)](fg:red bold)"
ahead = "[\uf63e${count}](fg:green bold)"
diverged = "[\u21d5\\(](fg:#979997 bold)[\uf63e${ahead_count}](fg:green bold)[\uf63b${behind_count}](fg:red bold)[\\)](fg:#979997 bold)"
behind = "[\uf63b${count}](fg:red bold)"
style = "bold blue"

[aws]
disabled = true

# programming languages settings
[golang]
symbol = "\ufcd1 "

[java]
symbol = "\ue256 "

[kotlin]
symbol = "\uf533 "

[lua]
symbol = "\ue620 "

[perl]
symbol = "\ue769 "

[php]
symbol = "\ue608 "

[python]
symbol = "\ue606 "

[rlang]
symbol = "\ufcd2 "

[ruby]
symbol = "\ue23e "

[rust]
symbol = "\ue7a8 "

[scala]
format = "via [$symbol ($version )]($style)"

[battery]
disabled = true
