format = """
$all$jobs$line_break$character
"""
add_newline = false

[character]
success_symbol = "[\u2570\u2500>](bold green)"
error_symbol = "[\u2570\u2500>](bold green)"

[username]
format = "[\u256d\u2500](bold green) [$user]($style) "
show_always = true

[hostname]
format = "@ [$hostname]($style) "
style = "bold fg:#d75f5f"
ssh_only = false

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
style = "bold blue"

[git_status]
staged = "[+\\(${count}\\)](fg:green bold)"
untracked = "[%\\(${count}\\)](fg:#ff92df bold)"
modified = "[!\\(${count}\\)](fg:red bold)"
stashed = "[?\\(${count}\\)](fg:yellow bold)"
renamed = "[r](fg:cyan bold)"
deleted = "[d](fg:red bold)"
ahead = "[\u21e1${count}](fg:green bold)"
diverged = "\u21d5[\u21e1${ahead_count}](fg:green bold)[\u21e3${behind_count}](fg:red bold)"
behind = "[\u21e3${count}](fg:red bold)"
style = "bold blue"

# programming languages settings
[java]
symbol = "\ue256 "

[kotlin]
symbol = "\uf533 "

[python]
symbol = "\ue606 "

[rlang]
symbol = "\ufcd2 "

[rust]
symbol = "\ue7a8 "

[battery]
disabled = true
