format = """
$all$jobs$line_break$character
"""
add_newline = false

[character]
success_symbol = "[\u2570\u2500>](bold green)"
error_symbol = "[\u2570\u2500>](bold green)"

[username]
format = "[\u256d\u2500](bold green) [$user]($style) "
show_always = true

[hostname]
format = "@ [$hostname]($style) "
style = "bold fg:#d75f5f"
ssh_only = false

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
style = "bold blue"

[git_status]
staged = "[+\\(${count}\\)](fg:white bold)"
untracked = "[%\\(${count}\\)](fg:#ff92df bold)"
modified = "[!\\(${count}\\)](fg:#ffa500 bold)"
stashed = "[?\\(${count}\\)](fg:yellow bold)"
renamed = "[r\\(${count}\\)](fg:cyan bold)"
deleted = "[d\\(${count}\\)](fg:#808080 bold)"
ahead = "[\uf102${count}](fg:green bold)"
diverged = "[\u21d5\\(](fg:#979997 bold)[\uf102${ahead_count}](fg:green bold)[\uf103${behind_count}](fg:red bold)[\\)](fg:#979997 bold)"
behind = "[\uf103${count}](fg:red bold)"
style = "bold blue"

[aws]
disabled = true

[battery]
disabled = true

# programming languages settings
[c]
symbol = "\ue61d "
commands = [ [ 'clang', '--version' ], [ 'gcc', '--version' ], [ 'cc', '--version' ] ]
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]
format = "via [$symbol($name(-$version) )]($style)"

[golang]
symbol = "\ue627 "

[java]
symbol = "\ue256 "

[kotlin]
symbol = "\ue634 "

[lua]
symbol = "\ue620 "

[perl]
symbol = "\ue769 "

[php]
symbol = "\ue608 "

[python]
symbol = "\ue606 "

[rlang]
symbol = "\ufcd2 "

[ruby]
symbol = "\ue23e "

[rust]
symbol = "\ue7a8 "

[scala]
format = "via [$symbol ($version )]($style)"
