#!/bin/bash
#
# xprofile

# monitors settings
xrandr --output DisplayPort-0 --primary --mode 1920x1080 --rotate normal --rate 165.00
xrandr --output HDMI-A-0 --mode 2560x1080 --rotate right --right-of DisplayPort-0

# start picom
picom -b

# turn off display sleeping
xset s off && xset dpms 0 0 0

# start unclutter
unclutter -b

# from .profile
export EDITOR=/usr/bin/nano
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# these needed to be up really early due to ST's LSP
export CARGO_HOME="${HOME}/.local/share/cargo"
export NPM_CONFIG_USERCONFIG="${HOME}/.config/npm/npmrc"
export RUSTUP_HOME="${HOME}/.local/share/rustup"
