#!/bin/bash

echo "bspwm: starting..." 1>&2
# kill lingering lemonbar, sxhkd and dunst
pkill -x powerlemon
pkill -x lemonbar
pkill -USR1 -x sxhkd
pkill dunst

bspc monitor DP-0 -d 壹 贰 参 肆 伍
bspc monitor HDMI-0 -d 捌 玖 拾

# remaining set up and variable declaration
export GDK_SCALE=2 &
export GDK_DPI_SCALE=0.4 &
gap=6
. ~/.private/env.bash

# setup wallpaper, lemonbar, sxhkd and dunst
feh --bg-fill ${WALLPAPER} --no-fehbg &
~/.config/lemonbar/powerlemon &
sxhkd &
dunst -config ~/.config/dunst/dunstrc &

# This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap ${gap}
for side in top right bottom left ; do
	bspc config ${side}_padding -${gap}
done
bspc config -m '^1' top_padding $((4-${gap}))

# configuration
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config automatic_scheme 		alternate
bspc config center_pseudo_tiled		false

# border config
bspc config border_width         	2
bspc config normal_border_color 	"#534A65"
bspc config focused_border_color	"#7c71dd"
bspc config presel_feedback_color 	"#ff5555"

# Apps settings
## 参 (terminal)
bspc rule -a ${TERMINAL^} desktop='^3' follow=on focus=on

### Building receptacles for 参
startup_lock_file=/tmp/bspwm-startup.lock
if [[ ! -f $startup_lock_file ]] ; then
	touch $startup_lock_file
	bspc desktop -f '^3'
	bspc node @/ -i
	bspc node @/ -p west -i
	bspc node @/2 -o 0.6 -p south -i
	bspc rule -a ${TERMINAL^}:primary -o node=@/1
	bspc rule -a ${TERMINAL^}:top -o node=@/2/1
	bspc rule -a ${TERMINAL^}:secondary -o node=@/2/2
fi

## 貳 (dev)
bspc rule -a Sublime_text desktop='^2' follow=on focus=on

## 壹 (browser)
bspc rule -a firefox desktop='^1' follow=on focus=on

## 捌 (reader/listener)
bspc rule -a Zathura desktop='^6' state=tiled follow=on focus=on
bspc rule -a jukebox desktop='^6' state=tiled follow=on focus=on
bspc rule -a Gpodder desktop='^6' state=tiled follow=on focus=on
bspc rule -a firefox:Toolkit desktop='^6' state=pseudo_tiled follow=on focus=on

## 玖 (pager)
bspc rule -a Slack desktop='^7' follow=on focus=on
bspc rule -a Sublime_merge desktop='^7' follow=on focus=on
bspc rule -a Insomnia desktop='^7' follow=on focus=on
bspc rule -a sshclient desktop='^7' follow=on focus=on

## 拾 (messenger)
bspc rule -a discord desktop='^8' follow=on focus=on

## 肆 (media)
bspc rule -a Lutris desktop='^4' follow=on focus=on
bspc rule -a Steam desktop='^4' state=pseudo_tiled follow=on focus=on
bspc rule -a mpv desktop='^4' follow=on focus=on
bspc rule -a vlc desktop='^4' follow=on focus=on
bspc rule -a Vlc desktop='^4' follow=on focus=on

### games are all in 肆
mygames=$(ls ${DATALAKE}/games/steam/steamapps/ | grep appmanifest | sed 's/[^0-9]*//g')
for game in ${mygames}; do
	bspc rule -a steam_app_$game desktop='^4' state=fullscreen follow=on
done &
bspc rule -a sc2_x64.exe desktop='^4' state=fullscreen follow=on
bspc rule -a Overwatch.exe desktop='^4' state=fullscreen follow=on

## floating
bspc rule -a Sakura state=floating rectangle=1010x450+455+315

## 伍 (floating)
FLOATING_DESKTOP_ID=$(bspc query -D -d '^5')

bspc subscribe node_add | while read -a msg ; do
	desk_id=${msg[2]}
	wid=${msg[4]}
	[[ ${FLOATING_DESKTOP_ID} == ${desk_id} ]] && bspc node "${wid}" -t floating
done &

echo "bspwm: finished setting up" 1>&2
