#!/bin/bash

echo "bspwm: starting..." 1>&2

# kill lingering lemonbar, sxhkd and dunst
pkill -x powerlemon
pkill -x lemonbar
pkill -USR1 -x sxhkd
pkill dunst

# set up monitors
declare -i mon_count=0
declare -a workspace
workspace[0]="壹 贰 参 肆 伍"
workspace[1]="捌 玖 拾"
MONITORS=$(xrandr -q | grep -oP "\K[a-zA-Z0-9\-]+?(?= connected)")
for mon in ${MONITORS} ; do
	bspc monitor ${mon} -d ${workspace[${mon_count}]}
	mon_count=$((${mon_count}+1))
done
unset mon_count
unset workspace
unset MONITORS
unset mon

# remaining set up and variable declaration
export GDK_SCALE=2 &
export GDK_DPI_SCALE=0.4 &
gap=6
. ~/.config/private/env.bash

# setup wallpaper, lemonbar, sxhkd and dunst
feh --bg-fill ${WALLPAPER} --no-fehbg &
~/.config/lemonbar/powerlemon &
sxhkd &
dunst -config ~/.config/dunst/dunstrc &

# This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap ${gap}
for side in top right bottom left ; do
	bspc config ${side}_padding -${gap}
done
bspc config -m '^1' top_padding $((4-${gap}))

# configuration
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config automatic_scheme 		alternate
bspc config center_pseudo_tiled		false

# border config
bspc config border_width         	2
bspc config normal_border_color 	"#534a65"
bspc config focused_border_color	${BSPWM_FOCUSED_BORDER}
bspc config presel_feedback_color 	"#ff5555"

# Apps settings
## 参 (terminal)
bspc rule -a primary desktop='^3' state=tiled follow=on focus=on

## 貳 (dev)
bspc rule -a Sublime_text desktop='^2' follow=on focus=on

## 壹 (browser)
bspc rule -a firefox:Navigator desktop='^1' state=tiled follow=on focus=on

## 肆 (media)
bspc rule -a mpv desktop='^4' state=tiled follow=on focus=on

## 肆/捌 (jukebox)
bspc rule -a jukebox desktop=${JUKEBOX_DESKTOP} state=tiled follow=on focus=on

## floating
bspc rule -a feh state=floating follow=on focus=on
bspc rule -a floatterm state=floating rectangle=1010x450+455+315
bspc rule -a calterm state=floating rectangle=700x1000+1201+46

. ${BSPWM_RULES}
[[ ${FLOATING_DESKTOP} ]] && . ${HOME}/.config/bspwm/floating_rules

bspc config external_rules_command ${HOME}/.config/bspwm/external_rules

echo "bspwm: finished setting up" 1>&2
