#!/bin/bash

. $(dirname $0)/panelConfig

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case ${line} in
		H*)
			host="${line#?}"
			;;
		T*)
			sysC="${line#?}"
			;;
		S*)
			sysR="${line#?}"
			;;
		W*)
			# bspwm's state
			wm=
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case ${item} in
					# [mM]*)
						# monitor state
						# [ $num_mon -lt 2 ] && shift && continue
						# wm="${wm}%{F${WHITE}}%{B${SEC_0}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						# ;;
					[fFoOuU]*)
						# desktop state
						FG=${GREY}
						UL=${SEC_0}
						case $item in
							[f]*)
								# free desktop
								;;
							[ou]*)
								# occupied and urgent desktop
								FG=${BLUE}
								;;
							[FOU]*)
								# focused occupied and urgent desktop
								FG=${YELLOW}
								UL=${YELLOW}
								;;
						esac
						wm="${wm}%{F${FG}}%{B${SEC_0}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
						;;
					# [LTG]*)
					# T*)
					# 	# node state
					# 	case $name in
					# 		F*)
					# 			name="Floating"
					# 			;;
					# 		T*)
					# 			name="Tiled"
					# 			;;
					# 		P*)
					# 			name="Pseudo-Tiled"
					# 			;;
					# 	esac
					# 	wm="${wm}%{F${WHITE}}%{B${SEC_0}}: ${name} %{B-}%{F-}"
					# 	;;
				esac
				shift
			done
			wm="${wm}%{F${SEC_0}}%{B${TRANSPARENT}}$(printf '%b'${LEFT_HARD_DIVIDER})%{B-}%{B-}%{F-}"
			;;
	esac
	printf "%s\n" "%{l}${host}${wm}%{c}${sysC}%{r}${sysR}"
done
