#!/bin/sh

# panel info setup
PANEL_FIFO=/tmp/panel-fifo
PANEL_WM_NAME=bspwm_panel

# bar height and width
BARHEIGHT=17
EDGEWIDTH=5
UPPERWIDTH=3
UNDERLINE_WIDTH=2

# fonts and icon 
FONT="Inconsolata for Powerline:style=Regular:pixelsize=$(($BARHEIGHT - 3)):antialias=true:hinting=1:letterSpace=-5:dpi=96"
ICONS="Inconsolata Nerd Font:style=Regular:pixelsize=$BARHEIGHT,3:letterSpace=-8:lineSpace=-2:dpi=96"
JPFONT=":pixelsize=$(($BARHEIGHT - 5)):lang=ja"

# colours: Modified Dracula
BG="#534a65"
FG="#d37961"
RED="#ff5555"
BLUE="#6272a4"
CYAN="#8be9fd"
GREEN="#50fa7b"
YELLOW="#ffb86c"
SALMON="#d37961"
BLACK="#212121"
WHITE="#f8f8f2"
GREY="#2d333f"
LIGHT_GREY="#979997"
PURPLE="#bd93f9"

SEC_0="#282a36"

TRANSPARENT="#66282a36"

# dividers
RIGHT_HARD_DIVIDER="\ue0b2"
RIGHT_SOFT_DIVIDER="\ue0b3"
LEFT_HARD_DIVIDER="\ue0b0"
LEFT_SOFT_DIVIDER="\ue0b1"

# icons
ARCH="\uf303"
MANJARO="\uf312"
CPU="\ufc06"
RAM="\uf85a"
PI="\uf315"
MUSIC="\uf885"
CLOCK="\ufa19"