#
# ~/.bashrc
#

[[ $- != *i* ]] && return

[[ -r /usr/share/bash-completion/bash_completion ]] && . /usr/share/bash-completion/bash_completion

xhost +local: > /dev/null 2>&1

complete -cf sudo

shopt -s checkwinsize
shopt -s expand_aliases
shopt -s histappend

## List of stuff to source for bash
. ~/.config/bash/env.bash
. ~/.config/bash/functions.bash
. ~/.config/bash/alias.bash
. ~/.config/bash/colour.bash
. ~/.config/private/env.bash
. /usr/share/nvm/init-nvm.sh

eval "$(pyenv init -)"
eval "$(starship init bash)"
